### ISSUE TITLE
How to resolve this? 

### ISSUE THREAD

**Issue by MATR1X0** [culturally/yin-Omega#3]
![image](https://github.com/culturally/yin-Omega/assets/99503441/7079bf3d-353f-4536-8bbc-c1e0a087846c)

**Comment by culturally** [comment]
You need to use country code with the number for example: The number is USA so you will use `+1`
so if the number looks like this _(555) 555-5555_
you will enter `+15555555555`. Also don’t forget that the api doesn’t work on certain countries. [Here is a good example about E.164 format and how to use it.](https://support.zendesk.com/hc/en-us/articles/4408823756570-What-are-the-accepted-phone-number-formats-for-Talk-#:~:text=164%20format.-,E.,164%20format%20is%20%2B16175551212.)
